# Generated by Django 3.2.13 on 2022-10-07 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_review_star"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="star",
        ),
    ]
